version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    expose:
      - 9411
    ports:
      - 9411:9411

  postgresql:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employees
      POSTGRES_PASSWORD: employees
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U employees -d employees'"]
      interval: 10s
      timeout: 2s
      retries: 10

  employees-app:
    image: employees-sb3:0.0.1-SNAPSHOT
    depends_on:
      postgresql:
        condition: service_healthy
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgresql/employees'
      SPRING_DATASOURCE_USERNAME: employees
      SPRING_DATASOURCE_PASSWORD: employees
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: 'http://zipkin:9411/api/v2/spans'
    ports:
      - 8080:8080
